export enum TileType {
  FLOOR = 0,
  WALL = 1,
  SHADOW = 2,
  DOOR = 3,
  WOOD_WALL = 4,
  GRASS = 5,
  LAVA = 6,
  KNIGHT_SPAWN = 7,
  DRAGON_SPAWN = 8,
  TREASURE = 9,
  DRAGON_WAYPOINT = 10,
  STAIRS = 11,
  ELEVATED_FLOOR = 12,
  ELEVATED_WALL = 13,
}

export interface TileProperties {
  walkable: boolean;
  blocksLOS: boolean;
  destructible: boolean;
  reducesDetection: boolean;
  damagePerSec: number;
  name: string;
  color: number;
}

export const TILE_PROPERTIES: Record<TileType, TileProperties> = {
  [TileType.FLOOR]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Floor',
    color: 0x333344,
  },
  [TileType.WALL]: {
    walkable: false,
    blocksLOS: true,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Wall',
    color: 0x555566,
  },
  [TileType.SHADOW]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: true,
    damagePerSec: 0,
    name: 'Shadow',
    color: 0x1a1a2e,
  },
  [TileType.DOOR]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Door',
    color: 0x886633,
  },
  [TileType.WOOD_WALL]: {
    walkable: false,
    blocksLOS: true,
    destructible: true,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Wood Wall',
    color: 0x997744,
  },
  [TileType.GRASS]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: true,
    damagePerSec: 0,
    name: 'Grass',
    color: 0x336633,
  },
  [TileType.LAVA]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 10,
    name: 'Lava',
    color: 0xff3300,
  },
  [TileType.KNIGHT_SPAWN]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Knight Spawn',
    color: 0x333344,
  },
  [TileType.DRAGON_SPAWN]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Dragon Spawn',
    color: 0x333344,
  },
  [TileType.TREASURE]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Treasure',
    color: 0x333344,
  },
  [TileType.DRAGON_WAYPOINT]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Dragon Waypoint',
    color: 0x333344,
  },
  [TileType.STAIRS]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Stairs',
    color: 0x555566,
  },
  [TileType.ELEVATED_FLOOR]: {
    walkable: true,
    blocksLOS: false,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Elevated Floor',
    color: 0x444455,
  },
  [TileType.ELEVATED_WALL]: {
    walkable: false,
    blocksLOS: true,
    destructible: false,
    reducesDetection: false,
    damagePerSec: 0,
    name: 'Elevated Wall',
    color: 0x666677,
  },
};
